(lang dune 3.11)

(name KA_equiv)

; (generate_opam_files true)

; (source
;  (github inessdv/UR2Phd_KAT))

; (authors "Author Name")

; (maintainers "Maintainer Name")

; (license LICENSE)

; (documentation https://url/to/documentation)

; (package
;  (name KA_equiv)
;  (synopsis "A short synopsis")
;  (description "A longer description")
;  (depends ocaml dune)
;  (tags
;   (topics "to describe" your project)))

; ; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
